### ISSUE TITLE
Why don't you use Vault's bank API???

### ISSUE THREAD

**Issue by Emibergo02** [cloudnode-pro/BankAccounts#118]
I see that you're not using vault bank api for banks. this is a big problem for economy systems that works on multi-server setups like RedisEconomy

**Comment by zefir-git** [comment]
Hi! I didn’t add the Vault Bank feature due to some incompatibilities with how BankAccounts handles transfers and transactions.

For instance, the transaction history feature would not work because Vault does not specify the recipient or source of the funds. This was particularly frustrating, so I decided to compromise by using a single account for Vault in which all transactions are recorded as to/from the server account.

For multi-server setups, you might try using the MariaDB driver for BankAccounts storage and sharing the same database across multiple servers. However, this approach hasn't been tested, and features like invoice notifications and "you received money" alerts won't work.

I'd love to hear if you have any ideas on how to overcome these issues.

**Comment by zefir-git** [comment]
I'm closing this issue as I didn't get a response. If you have additional information to add, please feel free to comment, and I can reopen the issue if necessary. For new ideas or to report bugs, kindly open a new issue. Thank you!
