### ISSUE TITLE
Optional account сreation on first join

### ISSUE THREAD

**Issue by SvinkaSunshine** [cloudnode-pro/BankAccounts#123]
Restore the option to not create a bank account for a player upon their first join on the server. This feature was previously available but was lost after the addition of Vault support.

It would be logical that if Vault integration is disabled in config.yml, the Vault account should not be created.

**Comment by zefir-git** [comment]
To confirm, disabling account creation on join will happen by setting `starting-balance: null` in the config.

However, if you have the Vault integration enabled, a starting Vault account with balance 0 will be created even if this is set to `null`. This is because Vault expects all players to have an account.

Also, if the starting balance is >= 0, then the account that is created has the type `Vault` even if Vault is disabled. This is because the Vault (aka "Checking") account is now always treated as the single default account for players.
