### ISSUE TITLE
What is the Vault account type?

### ISSUE THREAD

**Issue by Slinky142** [cloudnode-pro/BankAccounts#137]
hi I have a question. If you want to create a bank account, there are Business, Personal and Vault. What is the difference between Vault and the others?

**Comment by Slinky142** [comment]
and another question: how can I, for example, essentialsX transfer money to my bank account? and vice versa? So from the bank account to essentialsX?

**Comment by zefir-git** [comment]
We discussed this on Matrix. Posting here a similar explanation in case someone in the future stumbles upon this.

The Vault account type (named as "Checking" in the default config) is primarily used for the Vault integration. The Vault integration (disabled by default in config) enables compatibility between this plugin and other economy plugins, such as chest shops, withdraw money as item, etc. With the Vault integration enabled (and if you also have the Vault plugin installed), when other plugins try to access a player's money, they will see that player's Vault/Checking account. So if you want to spend money on a chest shop, transfer funds into your Vault/Checking account and the chest shop plugin will be able to use that. The chest shop seller will receive the funds in their Vault/Checking account.

The Vault account also works as all other accounts, allowing you to make transfers to/from it, etc. The only limitation is that players can only have 1 Vault account.

Since #131 (release 1.10.0-beta.1), you can use `@VaultAccountOwnerUsername` instead of the Vault account ID, example:

`/bank balance @Player123`

Without the Vault integration, transferring funds between plugins is not possible. Admins can manually transfer funds between BankAccounts and EssentialsX using `/bank setbal` and `/eco <give|take>` to manually adjust the balances.

If in the past you used a different economy provider plugin and want to switch to BankAccounts as the main economy provider (with Vault enabled), you can use the `/vault-convert` command to migrate the economy to BankAccounts. When testing this with EssentialsX, the conversion/migration did not work. It's recommended that you make a backup before converting economies.
