### ISSUE TITLE
MySQL data source support

### ISSUE THREAD

**Issue by lemonvace** [cloudnode-pro/BankAccounts#33]
Hi I have a question unzwar maybe you can do it with the plugin so that you can use MySQL as a database type and not just sqlite and Mariadb?

**Comment by lemonvace** [comment]
and somehow the translation doesn't work, so you can't set whether you want it in German or English

**Comment by lemonvace** [comment]
and how can you transfer money from EssentialsX to your personal account in the plugin, for example?

**Comment by lemonvace** [comment]
ok the thing with mysql can you let me know if you've checked if you can do it with mysql?

**Comment by zefir-git** [comment]
Currently, we support SQLite and MariaDB and must maintain two separate `.sql` files for setting up each DB. Adding MySQL will only add more complexity to the project. Even if you already use MySQL for other stuff, you could also install and run a MariaDB server on a different port.

If you don't want to bother setting up a database server, you can also use the `SQLite` option which will use a file (by default `bank.db`) to store all data. This also lets you easily create backups of your DB since all you have to do is copy the file.

If anyone sees a way to add MySQL support without adding too much complexity to the project, please feel free to open a pull request.
